### ISSUE TITLE
Oracle on the gpu

### ISSUE THREAD

**Issue by zeeyang** [mkeeter/mpr#3]
@mkeeter thank you for publishing this paper and code. On your "future work" slide, you mentioned blackbox oracle support. Would oracle just be a custom shader that bypasses interval evaluation and tape shortening?

**Comment by mkeeter** [comment]
There are probably a bunch of ways to handle it, but I can give some context.

In `libfive` (the CPU-side equivalent), I use nodes in the tree which take X,Y,Z coordinates and implement three core operations:
- Point-wise evaluation `f(x, y, z) -> d`
- Interval evaluation `f([xmin, xmax], [ymin, ymax], [zmin, zmax]) -> [dmin, dmax]`
- Gradient evaluation `f(x, y, z) -> df/dx, df/dy, df/dz`

These act as black-box nodes in the tree of math operations.

On the GPU, I think the fundamental approach would be similar; the question is of encoding and dispatch.

Each clause in the tree/tape is 8 bytes.  You'd probably want a dedicated opcode (`GPU_OP_ORACLE`), then use one of the other bytes as an indication that tells you what kind of oracle to use, e.g.

```
GPU_OP_ORACLE | output slot | oracle type  | spare data
1 bytes   | 1 byte      | 1 byte?      | remaining bytes
```

You could then plug this into the evaluation loop [here](https://github.com/mkeeter/mpr/blob/master/src/context.cu#L252), e.g.
```
case GPU_OP_ORACLE: {
    // Use the LHS byte as the oracle type
    switch (I_LHS(&d)) {
        case ORACLE_TYPE_MESH:
            // Pass XYZ coordinates to the oracle
            out = oracle_kernel_mesh_point(values[tile_index * 3],
                                           values[tile_index * 3 + 1],
                                           values[tile_index * 3 + 2]);
            break;
        case ... 
    }
}
```

There are a bunch of challenges here:
- Since GPUs don't really do dynamic linking, you'd have to know what kinds of oracles you're supporting in advance and link in those kernels at build time.
- It would be _very_ easy to blow up your register budget.  The existing kernels in `mpr` are hand-tuned to stay below 32 registers/thread, which is necessary for 100% occupancy, and performance starts degrading immediately if you surpass this limit.  (Marking the oracle kernels as `__noinline__` would probably be necessary)
- Writing the three core functions for a mesh is _hard_.  Folks are pretty good at mesh distance and ray queries, and you can fake gradient with finite differences, but I'm not sure how to approach the interval evaluation ("What's the min and max distance to the mesh within this volume?").  It doesn't have to be exact, just conservative, but it's still tricky.

**Comment by zeeyang** [comment]
Thank you for the thorough explaination @mkeeter. I re-read your paper and everything makes sense now. Point eval is the SDF. Interval eval is for traversing the octo-tree. Gradient eval + autodiff generates the normal map.

I'm going to try port this to Metal as a learning excercise (also because I want to play with the UI but don't have access to an nvidia machine). Will keep you updated!
